name: myapp
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^1.1.2
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  path_provider: ^2.1.1
  pdf: ^3.10.6
  printing: ^5.14.2
  go_router: ^14.1.1
  share_plus: ^12.0.1
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0
  intl: ^0.19.0
  open_filex: ^4.3.2
  image_cropper: ^11.0.0
  reorderable_grid_view: ^2.2.6
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
