name: myapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  pdf: ^3.11.3
  image_picker: ^1.2.1
  path_provider: ^2.1.5
  printing: ^5.14.2
  google_fonts: ^6.3.3
  flutter_bloc: ^9.1.1
  reorderable_grid_view: ^2.2.8
  shared_preferences: ^2.5.4
  go_router: ^17.0.1
  image: ^4.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
